### ISSUE TITLE
Angular 7.2.11 cannot find module 'ngx-kjua' 

### ISSUE THREAD

**Issue by atecey** [werthdavid/ngx-kjua#7]
Angular: 7.2.11
ngx-kjua: 1.3.1
kjua: 0.1.2

Imported into the root level app.module.ts using readme details.

`import { NgxKjuaModule } from 'ngx-kjua';`

ng serve throws the following error. Vs code highlights and shows the same:

`ERROR in src/app/app.module.ts(24,31): error TS2307: Cannot find module 'ngx-kjua'`

All dependencies are installed and visible in the node modules directory

**Comment by atecey** [comment]
Works ok with ngx-kjua:1.3.0

**Comment by werthdavid** [comment]
Seems like there was a problem with the build/bundeling.... Sorry for the inconvenience. It should be fixed with 1.3.2 (I updated the StackBlitz example and it works there)
